stages:
  - sync_code
  - lint
  - commit_check

variables:
  IMAGE_NAME: 'jacob169/shopifycli:1.1'

git_pull:
  stage: sync_code
  tags:
    - docker
  image:
    name: jacob169/alpine:latest
    pull_policy: 'if-not-present'
  rules:
    - if: $CI_PIPELINE_SOURCE == 'schedule' && $REMOTE_URL && $REMOTE_BRANCH && $ACCESS_TOKEN
      variables:
        TARGET_BRANCH: '$REMOTE_BRANCH'
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED == 'true' && $REMOTE_URL && $ACCESS_TOKEN
      variables:
        TARGET_BRANCH: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME'
  before_script:
    - git config --global user.name "$GITLAB_USER_NAME"
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global checkout.defaultRemote origin
  script:
    - echo "🔹 Target branch $TARGET_BRANCH"
    - git remote remove reforigin || true
    - git remote add reforigin "$REMOTE_URL"
    - git fetch reforigin || { echo "❌ Failed to fetch from $REMOTE_URL"; exit 1; }

    # Sync code from reforigin branch
    - echo "🔹 Start syncing code..."
    - git checkout -B reforigin_$TARGET_BRANCH
    - git pull reforigin $TARGET_BRANCH --no-rebase || { echo "❌ Failed to pull latest changes"; exit 1; }
    - git push "https://${CI_REGISTRY_USER}:glpat-32UEnRY9Na7XYppYNfxW@${CI_REPOSITORY_URL#*@}" "reforigin_$TARGET_BRANCH"

    # Reset current branch and push code
    - git branch -D $TARGET_BRANCH || true
    - git fetch origin
    - git switch --force --track origin/$TARGET_BRANCH
    - git merge reforigin_$TARGET_BRANCH --no-ff || { echo "❌ Merge conflict!"; exit 1; }
    - git push "https://${CI_REGISTRY_USER}:glpat-32UEnRY9Na7XYppYNfxW@${CI_REPOSITORY_URL#*@}" "HEAD:$TARGET_BRANCH"
    - echo "✅ Process completed successfully!"


prettier:
  stage: lint
  tags:
    - docker
  image:
    name: $IMAGE_NAME
    pull_policy: 'if-not-present'
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED == 'true'
      exists:
        - .prettierrc.json
  script:
    - npx prettier -c "{assets,config,layout,locales,sections,snippets,templates}/**/*.{css,js,json}" || exit_code=$?
    - if [ $exit_code == 2 ]; then echo "Prettier check failed"; exit 2; fi;

# stylelint:
#   stage: lint
#   tags:
#     - docker
#   image:
#     name: $IMAGE_NAME
#     pull_policy: 'if-not-present'
#   rules:
#     - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED == 'true'
#       exists:
#         - .stylelintrc.json
#   script:
#     - echo "🔹 Fetching latest changes from remote..."
#     - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME --prune --unshallow || git fetch --all --prune --unshallow
#     - echo "🔹 Checking for modified CSS files..."
#     - CHANGED_FILES=$(git diff --name-only origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME...HEAD -- '*.css' '*.scss' '*.sass')
#     - |
#       if [ -z "$CHANGED_FILES" ]; then
#         echo "✅ No CSS/SASS/Liquid files changed. Skipping Stylelint."
#         exit 0
#       fi
#     - echo "🔹 Running Stylelint on modified files:"
#     - echo "$CHANGED_FILES"
#     - npx stylelint $CHANGED_FILES

check_commit_msg:
  stage: commit_check
  tags:
    - docker
  image:
    name: $IMAGE_NAME
    pull_policy: 'if-not-present'
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED == 'true'
      exists:
        - commitlint.config.js
  script:
    - npx commitlint --from $CI_MERGE_REQUEST_DIFF_BASE_SHA --to $CI_COMMIT_SHA

check_commit_author:
  stage: commit_check
  tags:
    - docker
  image:
    name: $IMAGE_NAME
    pull_policy: 'if-not-present'
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED == 'true'
      exists:
        - COMMIT_AUTHOR
  script:
    - |
      echo "Check commit author"
      echo "Step 1/2"
      LIST_AUTHOR="$(npx git-raw-commits --from $CI_MERGE_REQUEST_DIFF_BASE_SHA --to $CI_COMMIT_SHA --pretty=format:"%ae")"
      while IFS= read -r commitline; do
          FLAG_TRUE=0
          while read -r line; do
              if [[ "$commitline" == *"$line"* ]]; then
                  FLAG_TRUE=1
              fi
          done < COMMIT_AUTHOR
          if [ "$FLAG_TRUE" == "0" ]; then
              echo "This commit is not allow: $commitline"
              echo "Allow list"
              cat COMMIT_AUTHOR
              exit 1
          fi
      done <<< "$LIST_AUTHOR"
      echo "Done"

      echo "Step 2/2"
      LIST_COMMIT="$(npx git-raw-commits --from $CI_MERGE_REQUEST_DIFF_BASE_SHA --to $CI_COMMIT_SHA --pretty=format:"%ce")"
      while IFS= read -r commitline; do
          FLAG_TRUE=0
          while read -r line; do
              if [[ "$commitline" == *"$line"* ]]; then
                  FLAG_TRUE=1
              fi
          done < COMMIT_AUTHOR
          if [ "$FLAG_TRUE" == "0" ]; then
              echo "This commit is not allow: $commitline"
              echo "Allow list"
              cat COMMIT_AUTHOR
              exit 1
          fi
      done <<< "$LIST_COMMIT"
      echo "Done"

      exit 0;
  allow_failure: true
